/* Zusätzliche Texte der v2-Gestaltung (Interaktionen, neue Sektionen). Die Seitentexte selbst liegen in de.ts / en.ts. */
export const v2 = {
  de: {
    torchHint: 'Bewegen Sie das Licht.',
    torchHintTouch: 'Berühren Sie das Bild.',
    scroll: 'Weiterlesen',
    statement: ['Mehr als eine Jagd.', 'Ein Stück echtes Afrika —', 'im ersten Licht, zu Fuß, mit Geduld.'],
    promisesTitle: 'Drei Dinge, auf die Sie sich verlassen können',
    film: { title: 'Die letzten hundert Meter.', sub: 'Hier hört das Reden auf. Der Stock steht, die Büchse liegt an — und für ein paar Sekunden ist nichts anderes mehr wichtig.', play: 'Film abspielen', pause: 'Film anhalten', sound: 'Ton an', mute: 'Ton aus' },
    rail: { title: 'Wer hier zu Hause ist', hint: 'Scrollen — und die Fährte aufnehmen', more: 'Alle 32 Wildarten mit Preisen', drag: 'Ziehen' },
    speciesNote: { giraffe: 'Steht plötzlich über den Akazien — lautlos, riesig', zebra: 'Zieht im Morgennebel über die Ebene', buffalo: 'Der schwarze Fels im Dickicht. Herzschlag inklusive', nyala: 'Tritt im letzten Licht aus dem Dornveld', hartebeest: 'Der Läufer der offenen Ebenen', warthog: 'Kommt zur Suhle, wenn die Hitze steht' },
    films: {
      title: 'Sehen Sie selbst, wie das Revier atmet.',
      sub: 'Drei kurze Aufnahmen aus dem Revier — Pirsch, Dornveld und die Weite dazwischen. Ohne Musik, ohne Schnittgewitter.',
      note: 'Mit Originalton. Die Filme starten erst auf Klick.',
      play: 'Film abspielen',
      items: [
        { title: 'Anpirschen', meta: '36 Sekunden · Bushveld', text: 'Vom Fahrzeug ins Gelände: der Weg zum Ansitz, Schritt für Schritt, mit Professional Hunter und Tracker.' },
        { title: 'Auf der Pirsch', meta: '30 Sekunden · Goldenes Grasland', text: 'Später Nachmittag im hohen Gras, die Gruppe geht auf Fährte.' },
        { title: 'Im Dornveld', meta: '28 Sekunden · Morgennebel', text: 'Nebel über der Ebene, kurz bevor die Sonne durchkommt.' },
      ],
    },
    day: { title: 'Ein Tag im Revier', sub: 'Vom ersten Kaffee im Dunkeln bis zum letzten Büchsenlicht — so vergeht ein Jagdtag bei uns.' },
    lodge: { title: 'Nach dem Tag im Revier — ankommen.', cards: [
      { t: 'Das Haupthaus', x: 'Sechs Luxuszimmer, jedes mit eigenem Balkon, dazu eine Suite im eigenen Gebäude. Klimaanlage, eigenes Bad — und abends der Blick vom Balkon, wenn der Himmel orange wird.' },
      { t: 'Hunter’s Camp', x: 'Drei rustikale Häuser, ein Stück abseits, mit eigenem Wohnbereich und Küche: für Jagdgruppen, die abends unter sich sein wollen.' },
      { t: 'Pool, Lapa & Feuer', x: 'Mittags am Pool, abends unter dem Reetdach der Lapa: Braai, Wildbret, ein Glas Rotwein — und Geschichten, die mit jedem Erzählen ein Stück größer werden.' },
    ] },
    about: { title: 'Von klein auf Jäger.', title2: 'Heute Gastgeber.', cta: 'Wild Wessels kennenlernen' },
    cta: { title: 'Erzählen Sie uns von Ihrer', em: 'Wunschjagd.', text: 'Wir melden uns persönlich, sprechen über Reisezeit, Wildarten und Begleitpersonen — und schreiben Ihnen ein Angebot, hinter dem wir stehen.', button: 'Unverbindlich anfragen', mail: 'oder schreiben Sie direkt an' },
    trophy: { title: 'Trophäengalerie', text: 'Bilder erlegten Wildes zeigen wir bewusst nur auf Wunsch. Jedes Bild bleibt verdeckt, bis Sie es aufdecken.', reveal: 'Bild aufdecken', hide: 'Wieder verdecken', all: 'Alle aufdecken', none: 'Alle verdecken', open: 'Bild öffnen', zoom: 'Vergrößern' },
    facts: { title: 'Die Farm in Zahlen' },
    gallery: { open: 'Vergrößern', close: 'Schließen', prev: 'Zurück', next: 'Weiter' },
  },
  en: {
    torchHint: 'Move the light.',
    torchHintTouch: 'Touch the picture.',
    scroll: 'Keep reading',
    statement: ['More than a hunt.', 'A piece of real Africa —', 'at first light, on foot, with patience.'],
    promisesTitle: 'Three things you can count on',
    film: { title: 'The last hundred metres.', sub: 'This is where the talking stops. The sticks go up, the rifle settles — and for a few seconds nothing else matters.', play: 'Play film', pause: 'Pause film', sound: 'Sound on', mute: 'Sound off' },
    rail: { title: 'Who lives here', hint: 'Scroll — and pick up the track', more: 'All 32 species with prices', drag: 'Drag' },
    speciesNote: { giraffe: 'Suddenly there above the acacias — silent, enormous', zebra: 'Drifts across the plain in morning mist', buffalo: 'The black rock in the thicket. Heartbeat included', nyala: 'Steps out of the thornveld in the last light', hartebeest: 'The runner of the open plains', warthog: 'Comes to the wallow when the heat stands still' },
    films: {
      title: 'See for yourself how the veld breathes.',
      sub: 'Three short takes from the concession — the stalk, the thornveld and the wide country in between. No music, no cutting frenzy.',
      note: 'With original sound. The films only start when you click.',
      play: 'Play film',
      items: [
        { title: 'Moving in', meta: '36 seconds · Bushveld', text: 'From the vehicle into the field: the walk to the stand, step by step, with professional hunter and tracker.' },
        { title: 'On the stalk', meta: '30 seconds · Golden grassland', text: 'Late afternoon in tall grass, the party following tracks.' },
        { title: 'In the thornveld', meta: '28 seconds · Morning mist', text: 'Mist over the plain, just before the sun breaks through.' },
      ],
    },
    day: { title: 'A day in the field', sub: 'From the first coffee in the dark to the last shooting light — how a hunting day passes here.' },
    lodge: { title: 'After the day in the field — come home.', cards: [
      { t: 'The main house', x: 'Six luxury rooms, each with its own balcony, plus a suite in its own building. Air-conditioning, en-suite bathrooms — and the view from the balcony at dusk.' },
      { t: 'Hunter’s Camp', x: 'Three rustic houses set slightly apart, with their own living area and kitchen: for hunting parties who want the evening to themselves.' },
      { t: 'Pool, lapa & fire', x: 'Midday by the pool, evenings under the thatched lapa: braai, venison, a glass of red — and stories that grow a little with every telling.' },
    ] },
    about: { title: 'Hunters since childhood.', title2: 'Hosts today.', cta: 'Meet Wild Wessels' },
    cta: { title: 'Tell us about the hunt', em: 'you have in mind.', text: 'We reply personally, talk through dates, species and companions — and send you an offer we stand behind.', button: 'Enquire without obligation', mail: 'or write directly to' },
    trophy: { title: 'Trophy gallery', text: 'We show images of harvested game only on request. Every picture stays covered until you reveal it.', reveal: 'Reveal picture', hide: 'Cover again', all: 'Reveal all', none: 'Cover all', open: 'Open picture', zoom: 'Enlarge' },
    facts: { title: 'The farm in numbers' },
    gallery: { open: 'Enlarge', close: 'Close', prev: 'Previous', next: 'Next' },
  },
} as const;
export type V2 = typeof v2.de;
